linter:
  rules:
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    always_require_non_null_named_parameters: true

analyzer:
  
  exclude:
    - "test/**"
    - "build/**"

pedantic:
  include:
    - "package:pedantic/analysis_options.yaml"


